name: PR Checks

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ "develop" ]

jobs:
  unit-tests:

    name: Unit Tests

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Run tests
      run: ./run_test.sh